<!-- Forms Presentation -->
<section id="forms-content" class="page-content">
	<section id="forms-menu" class="twelvecol">
		<ul id="forms-menu-list" class="">
			<li class="form-item-row">
				<ul class="form-item">
					<a href="forms/cremation-form">
						<li class="form-item-img"><img src="/images/cremation_thumb.png" alt="Cremation Form" /></li>
						<li class="form-item-caption">Cremation Authorization Form</li>
					</a>
				</ul>
				<ul class="form-item">
					<a href="forms/embalming-form">
						<li class="form-item-img"><img src="/images/enbalming_thumb.png" alt="Embalming Form" /></li>
						<li class="form-item-caption">Embalming Form</li>
					</a>
				</ul>
				<ul class="form-item">
					<a href="forms/registration-form">
						<li class="form-item-img"><img src="/images/registration_thumb.png" alt="Registration Form" /></li>
						<li class="form-item-caption">Registration Form</li>
					</a>
				</ul>
			</li>
		</ul>
	</section>
</section>