<!-- Forms Presentation -->
<section id="forms-content" class="page-content">
	<nav id="forms-nav" class="twocol">
		<hgroup>
			<h5>--- Please Select ---</h5>
		</hgroup>
		<a href="/forms/registration">Registration Form</a>
		<a href="/forms/cremation">Cremation Authorization Form</a>
		<a href="/forms/embalming">Embalming Form</a>
	</nav>
	<section id="form-wrapper" class="tencol">

	</section>
</section>