<section id="admin-content" class="page-content">
	<header>
		<h1>Threadgill Memorial Administration</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol">
		<nav id="forms-nav" class="page-menu">
			<hgroup>
				<h6>--- Welcome, <b><? echo $this->identity->name; ?></b> ---</h6>
			</hgroup>
			<ul>
				<li><a href="/admin">Site Stats</a></li>
				<li><a href="/admin/products">Product Administration</a></li>
				<li><a href="/admin/maintenance">Site Maintenance</a></li>
				<li><a href="/admin/logout">Logout</a></li>
			</ul>
		</nav>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Site Stats</h5>
			</hgroup>
		</header>
		<section class="sub-content-wrapper">
			<article>
				<p>Coming soon!</p>
			</article>
		</section>
	</section>
	<section class="clear-15"></section>
</section>