<section id="admin-content" class="page-content">
	<header>
		<h1>Threadgill Memorial Administration</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol">
		<nav id="forms-nav" class="page-menu">
			<?php echo $this->partial('partials/_nav-admin.phtml', $this->identity); ?>
		</nav>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Site Stats</h5>
			</hgroup>
		</header>
		<section class="sub-content-wrapper">
			<article>
				<p>Coming soon!</p>
			</article>
		</section>
	</section>
	<section class="clear-15"></section>
</section>
