<section id="admin-content" class="page-content">
	<header>
		<h1>Threadgill Memorial Administration</h1>
	</header>
	<section class="clear-15"></section>
	<section class="onecol"></section>
	<section class="elevencol last content-wrapper">
		<header>
			<hgroup>
				<h5>Login</h5>
			</hgroup>
		</header>
		<section class="sub-content-wrapper">
			<form action="/admin/index/login" method="post">
				<!-- Decedent Information -->
				<fieldset>
					<header>
						<h6>User Login:</h6>
					</header>
					<!-- First Row -->
					<ul class="form-row twelvecol last">
						<li class="twelvecol last">
							<ul class="twelvecol last">
								<li class="twocol"></li>
								<li class="twocol lbl"><label for="name">Name: *</label></li>
								<li class="fourcol last"><input name="name" type="text" autofocus></li>
							</ul>
						</li>
					</ul>
					<!-- Second Row -->
					<ul class="form-row twelvecol last">
						<li class="twelvecol last">
							<ul class="twelvecol last">
								<li class="twocol"></li>
								<li class="twocol lbl"><label for="password">Password: *</label></li>
								<li class="fourcol last"><input type="password" name="password"></li>
							</ul>
						</li>
					</ul>
				</fieldset>
				<input type="submit" class="submit login-submit" value="login">
			</form>
		</section>
	</section>
	<section class="clear-15"></section>
</section>
