<section id="testimonials-content" class="page-content">
	<header>
		<h1>Testimonials</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol page-menu">
		<aside class="featured-quote">
			<span class="quote">&ldquo;</span>
			The peace of helping place a quilt over Dad and then seeing him leave in a white van instead of a dark hearse made so much of a difference to me. I just felt that he was riding with <span class="emph">someone who cared</span> for him too, off on to the next adventure. It was so much <span class="emph">more peaceful than I ever imagined</span> it could be.Thank you for all the little things that all added up to so much!
			<span class="quote">&rdquo;</span> 
			<span class="byline"> - Linda Gaudreau 2012</span>
		</aside>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>What our customers say about us:</h5>
			</hgroup>
		</header>
		<section>
			<article>
				<p>
					"When I referred my friend to you, I knew you would serve their family well, what I didn't expect was how good you made me look to my dearest friend.  Thank you so much for going above and beyond what was expected."
				</p>  
				<address rel="author">SC 2009</address>
			</article>
			<article>
				<p>
					"...as we remember our mother and the day of her service, our cup overflows with the tenderness, exceptional service and life long memories that we now have. Each family member upon their return home has commented on how special they felt and how choice the service was because of your ability to serve our family. Thank You!!"
				</p>  
				<address rel="author">JS 2009</address>
			</article>
			<article>
				<p>
					"I found you on the internet, called you from New York, had your company prepare and transport my 'Gammy' to Texas.  Your company was outstanding, effective, handled unexpected family members with superb warmth and tenderness in Oregon, organized via phone all arrangements in Texas and things went so smooth because of your professionalism, skill, and kindness.  We felt we were led to find you and never questioned our long distance decision. We never met, but I will never forget. Thank you!!"
				</p>
			</article>
			<article>
				<p>
					"We aren't the type that criticize, but it was FLAWLESS; absolutely flawless, amazing and so gentle."
				</p>  
				<address rel="author">DC 2009</address>
			</article>
			<article>
				<p>
					"I will refer you to everyone I know, I am thrilled that you made arrangements in my home. I have done this for several family members and this was by far the most comfortable, most inexpensive and smoothest. Without stepping out my door, flowers, cemetery and funeral arrangements were made and it was excellent"
				</p>  
				<address rel="author">JR 2008</address>
			</article>
<!-- 

“I’m so glad I found you…I had heard of you for years and you’re back just in time for my family!   Thank you"                            SF 2008

“God sent you to us…and you were just the right person for our family”. 
MM 2008

“What would we have done without you?”                    MJ 2007

“Oh we wish we had used you last time”.                    RS 2007  -->
			</article>
		</section>
	</section>
	<section class="clear-15"></section>
</section>