<section id="veterans-content" class="page-content">
	<header>
		<h1>Veterans</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol page-menu">
		
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>We love our veterans:</h5>
			</hgroup>
		</header>
		<section>
			
		</section>
	</section>
	<section class="clear-15"></section>
</section>