<section id="services-content" class="page-content">
	<header>
		<h1>Our Services</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol page-menu">
		<nav id="products-nav" class="">
		<hgroup>
			<h6>--- Please Select ---</h6>
		</hgroup>
		<ul>
			<li><a href="/services">Funeral Services</a></li>
			<li><a href="/services/pre-planning">Pre-Planning</a></li>
			<li><a href="/services/veterans">Veterans</a></li>
		</ul>
	</nav>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Memorial Services</h5>
			</hgroup>
		</header>
		<section>
			<figure class="fourcol">
				<img src="/images/funeral-service.png" alt="funeral service" />
			</figure>
			<article>
				<p>
					A Funeral Service typically means a casketed human body is present at the service.  (The casket does not necessarily need to be open) This service can be held anywhere the family chooses but sometimes is limited to a funeral chapel, church, cemetery or a facility where they allow casketed remains for a service.
				</p>
				<p>
					We assist families in these decisions and help them take into consideration the needs of family members.  We look at ourselves more as ushers than funeral directors.  There is no fault or blame,  right or wrong when decisions made by family members meet families long term needs.
				</p>
			</article>
		</section>
	</section>
	<section class="clear-15"></section>
</section>