<section id="services-content" class="page-content">
	<header>
		<h1>Our Services</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol page-menu">
		<nav id="products-nav" class="">
		<hgroup>
			<h6>--- Please Select ---</h6>
		</hgroup>
		<ul>
			<li><a href="/services/pre-planning">Pre-Planning</a></li>
			<li><a href="/services/online-memorials">Online Memorials</a></li>
			<li><a href="/services/obituaries">Obituaries</a></li>
			<li><a href="/services/veterans">Veterans</a></li>
			<li><a href="/services/social-security">Social Security</a></li>
			<li><a href="/services/death-certificates">Death Certificates</a></li>
			<li><a href="/services/after-care">after-care</a></li>
		</ul>
	</nav>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>What we do</h5>
			</hgroup>
		</header>
	</section>
	<section class="clear-15"></section>
</section>