<section id="services-content" class="page-content">
	<header>
		<h1>Our Services</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol page-menu">
		<nav id="products-nav" class="">
		<hgroup>
			<h6>--- Please Select ---</h6>
		</hgroup>
		<ul>
			<li><a href="/services">Funeral Services</a></li>
			<li><a href="/services/pre-planning">Pre-Planning</a></li>
			<li><a href="/services/veterans">Veterans</a></li>
		</ul>
	</nav>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Pre-Planning,  Pre-Paid Funeral or Cremation Services</h5>
			</hgroup>
		</header>
		<section>
			<figure class="fourcol">
				<img src="/images/funeral-planning.jpg" alt="funeral planning" />
			</figure>
			<article>
				<p>
					There are lots of theories, opinions and techniques represented on all sides of the Funeral industry.
				</p>
				<p>
					The truth of Pre-planning and Pre-paying is quite simple:
				</p>
				<blockquote>
					<ul>
						<li>Is it necessary?</li>
						<li>Is it financially practical?</li>
						<li>Is it the right time and right reason?</li>
						<li>Should it be irrevocable?</li>
					</ul>
				</blockquote>
				<p>
					Ron Threadgill is a Licensed Insurance Agent and Licensed Insurance Consultant in Oregon and has almost 20 years' experience in the financial planning industry including the funeral planning industry.
				</p>
			</article>
		</section>
	</section>
	<section class="clear-15"></section>
</section>