<section id="services-content" class="page-content">
	<header>
		<h1>Our Services</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol page-menu">
		<nav id="products-nav" class="">
		<hgroup>
			<h6>--- Please Select ---</h6>
		</hgroup>
		<ul>
			<li><a href="/services">Funeral Services</a></li>
			<li><a href="/services/pre-planning">Pre-Planning</a></li>
			<li><a href="/services/veterans">Veterans</a></li>
		</ul>
	</nav>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Veterans</h5>
			</hgroup>
		</header>
		<section>
			<figure class="fourcol">
				<img src="/images/flags.png" alt="flags" />
			</figure>
			<article>
				<p>
					We Love our Veterans!  We honor our Veterans!  We have arranged services for Veterans with no family or friends present and have seen to it that they receive Military Honors. 
				</p>
				<p>
					We have facilitated several times now while serving a person classified as an "indigent"  and with some research found their families, their military documents and arranged for internment with Military Honors!
				</p>
				<p>
					We have designed and made our own Veterans Passing quilt with matching pillow case.  We enter a home or facility where a Veteran has transitioned with a deep blue quilt on our cot with Eagles flying and within their talons carrying waving American Flags.
				</p>
				<p>
					As we exit, the reversible quilt displays hundreds or waving American Flags with a matching pillow case.  Not yet has any family member or staff member not stopped and admired their loved one being transported toward their military honors.
				</p>
				<p>
					We have created a "Veterans Brochure" with all the specific details on Veterans benefits specifically burial benefits, how to replace key veteran discharge documents.  Soon this brochure will be available on our website.
				</p>
			</article>
		</section>
	</section>
	<section class="clear-15"></section>
</section>