<section id="services-content" class="page-content">
	<header>
		<h1>Our Services</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol page-menu">
		<nav id="products-nav" class="">
		<hgroup>
			<h6>--- Please Select ---</h6>
		</hgroup>
		<ul>
			<li><a href="/services">Funeral Services</a></li>
			<li><a href="/services/pre-planning">Pre-Planning</a></li>
			<li><a href="/services/veterans">Veterans</a></li>
		</ul>
	</nav>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Veterans</h5>
			</hgroup>
		</header>
		<section>
			<figure class="fourcol">
				<img src="/images/funeral-service.png" alt="funeral service" />
			</figure>
			<article>
				<p>
					We will assist your family in planning a funeral and choosing the options that suit your family's needs and your loved one's wishes. We are able to assist you in holding services in a wide variety of areas. From our chapel, to your church or at the cemetery we are able to prepare a meaningful service to honor your loved one. We will listen to your family and help to arrange a celebration of your loved one's life through whatever means you choose.
				</p>
			</article>
		</section>
	</section>
	<section class="clear-15"></section>
</section>