<section class="twelvecol product-edit-row accordion">
	<header class="twelvecol accordion-header closed">
		<hgroup>
			<h2 class=""><?php echo $this->name; ?></h2>
			<ul>
				<li>Delete? </li>
				<li><input type="checkbox" name="product-edit-delete"></li>
			</ul>
			<span class="icon icon-plus"></span>
		</hgroup>
	</header>
<!-- 	<section class="clear-1"></section> -->
<section class="accordion-content twelvecol">
	<ul class="twelvecol">
	<li><input type="hidden" name="row-id" value="<?php echo $this->id; ?>"></li>
	<!-- Name -->
	<li class="tencol">
		<ul>
			<li class="twelvecol">Name:</li>
			<li class="twelvecol"><input type="text" name="product-name" value="<?php echo $this->name; ?>"></li>
		</ul>
	</li>
	<!-- Photo -->
	<li class="fourcol">
		<ul>
			<li>Photo:</li>
			<li>
				<figure class="product-image">
					<img src="<?php echo $this->photo_uri; ?>" alt="<?php echo $this->photo_name; ?>" class="current-photo">
				</figure>
			</li>
			<li><input type="file" name="product-photo"></li>
		</ul>
	</li>
	<li class="sevencol last">
		<ul>
			<!-- price -->
			<li>
				<ul class="twelvecol">
					<li>Price:</li>
					<li><input type="text" name="product-price" value="<?php echo $this->price; ?>"></li>
				</ul>
			</li>
			<!-- type -->
			<li class="twelvecol">
				<ul>
					<li>Type:</li>
					<li>
						<select name="product-type">
							<?php if($this->type == 'urns'): ?>
							<option value="urns" selected>Urn</option>
							<option value="caskets">Casket</option>
							<?php else :  ?>
							<option value="caskets" selected>Casket</option>
							<option value="urns">Urn</option>
							<?php endif; ?>
						</select>
					</li>
				</ul>
			</li>
			<!-- isVisible -->
			<li class="twocol">
				<ul>
					<li>Visible:</li>
					<?php if($this->is_visible == 'true'): ?>
					<li><input type="checkbox" name="product-visibility" checked></li>
					<?php else: ?>
					<li><input type="checkbox" name="product-visibility"></li>
					<?php endif; ?>
				</ul>
			</li>
		</ul>
	</li>
</ul>
<ul class="form-row twelvecol last">
	<li class="twocol lbl">Product Tags:</li> 
	<li class="eightcol"><input type="text" name="product-tags" placeholder="use a comma separated list like: (white, metal, less-expensive, etc)" value="<?php echo unserialize($this->tags); ?>"></li>
</ul>
<ul class="twelvecol">
	<li>Description</li>
	<li class="elevencol"><textarea name="product-desc"><?php echo $this->description; ?></textarea></li>
</ul>
<section class="clear-1"></section>
</section>
</section>
