<section class="twelvecol product-edit-row accordion">
	<header class="twelvecol accordion-header closed">
		<hgroup>
			<h2 class=""><?php echo $this->name; ?></h2>
			<ul>
				<li>Delete? </li>
				<li><input type="checkbox" name="product-edit-delete"></li>
			</ul>
			<span class="icon icon-plus"></span>
		</hgroup>
	</header>
<!-- 	<section class="clear-1"></section> -->
<section class="accordion-content twelvecol">
	<ul class="twelvecol">
	<li><input type="hidden" name="row-id" value="<?php echo $this->id; ?>"></li>
	<!-- Name -->
	<li class="twelvecol">
		<ul>
			<li class="twelvecol">Name:</li>
			<li class="eightcol"><input type="text" name="product-name" value="<?php echo $this->name; ?>"></li>
		</ul>
	</li>
	<!-- price -->
	<li class="twocol">
		<ul>
			<li>Price:</li>
			<li><input type="text" name="product-price" value="<?php echo $this->price; ?>"></li>
		</ul>
	</li>
	<!-- type -->
	<li class="twocol">
		<ul>
			<li>Type:</li>
			<li>
				<select name="product-type">
					<?php if($this->type == 'urns'): ?>
					<option value="urns" selected>Urn</option>
					<option value="caskets">Casket</option>
					<?php else :  ?>
					<option value="caskets" selected>Casket</option>
					<option value="urns">Urn</option>
					<?php endif; ?>
				</select>
			</li>
		</ul>
	</li>
	<!-- isVisible -->
	<li class="onecol">
		<ul>
			<li><?php echo $this->is_visible; ?></li>
			<li>Visible:</li>
			<?php if($this->is_visible == 'true'): ?>
			<li><input type="checkbox" name="product-visibility" checked></li>
			<?php else: ?>
			<li><input type="checkbox" name="product-visibility"></li>
			<?php endif; ?>
		</ul>
	</li>
	<!-- Photo -->
	<li class="sixcol last">
		<ul>
			<li>Photo:</li>
			<li><input type="text" title="<?php echo $this->photo_name; ?>" value="<?php echo $this->photo_name; ?>" readonly></li>
			<li><input type="file" name="product-photo"></li>
		</ul>
	</li>
</ul>
<ul class="form-row twelvecol last">
	<li class="threecol lbl"><label for="product-tags">Product Tags: </label></li> 
	<li class="eightcol"><input type="text" name="product-tags" placeholder="use a comma separated list like: (white, metal, less-expensive, etc)" value="<?php echo unserialize($this->tags); ?>"></li>
</ul>
<ul class="twelvecol">
	<li>Description</li>
	<li class="elevencol"><textarea name="product-desc"><?php echo $this->description; ?></textarea></li>
</ul>
<section class="clear-1"></section>
</section>
</section>