<section id="products-content" class="page-content">
	<header>
		<h1>Our Products</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol page-menu">
		<nav id="products-nav" class="">
		<hgroup>
			<h6>--- Please Select ---</h6>
		</hgroup>
		<ul>
			<li><a href="/forms">Caskets</a></li>
			<li><a href="/forms/cremation">Urns</a></li>
		</ul>
	</nav>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Featured caskets and urns</h5>
			</hgroup>
		</header>
		<section class="accordion product-listing">
			<header>
			</header>
			<section class="accordion-content">
			</section>
		</section>
	</section>
	<section class="clear-15"></section>
</section>