<?php $this->headScript()->appendFile('/scripts/application/products/scripts.js'); ?>
<section id="products-content" class="page-content">
	<header>
		<h1>Our Products</h1>
	</header>
	<section class="clear-15"></section>
	<section class="onecol page-menu">
		<!-- <nav id="products-nav" class="">
			<hgroup>
				<h6>--- Please Select ---</h6>
			</hgroup>
			<ul>
				<li><a href="/products/caskets">Caskets</a></li>
				<li><a href="/products/urns">Urns</a></li>
			</ul>
		</nav> -->
	</section>
	<section class="elevencol last content-wrapper">
		<header>
			<hgroup>
				<h5>Featured caskets and urns</h5>
			</hgroup>
		</header>
		<section class="items-wrapper">
			<!-- First -->
			<section class="product-listing twelvecol last">
				<figure class="product-image threecol">
					<img src="/images/caskets/atlantic-white.jpg" alt="atlantic-white">
				</figure>
				<section class="product-desc eightcol last">
					<header class="twelvecol last">
						<hgroup class="ninecol">
							<h5 class="product-title">
								Sterling 18 gauge steel
							</h5>
						</hgroup>
						<hgroup class="threecol last">
							<h6 class="product-price">$2720</h6>
						</hgroup>
					</header>
					<article class="product-details">
						<p>Antique White Shaded Silver Rose finish with Pink Crepe interior, also comes in Black Cherry, Empire Blue, Grecian Gold and Storm Blue finish</p>
					</article>
				</section>
			</section>
			<!-- Second -->
			<section class="product-listing twelvecol last">
				<figure class="product-image threecol">
					<img src="/images/urns/etienne-butterfly.png" alt="atlantic-white">
				</figure>
				<section class="product-desc eightcol last">
					<header class="twelvecol last">
						<hgroup class="ninecol">
							<h5 class="product-title">
								Sterling 18 gauge steel
							</h5>
						</hgroup>
						<hgroup class="threecol last">
							<h6 class="product-price">$2720</h6>
						</hgroup>
					</header>
					<article class="product-details">
						<p>Antique White Shaded Silver Rose finish with Pink Crepe interior, also comes in Black Cherry, Empire Blue, Grecian Gold and Storm Blue finish</p>
					</article>
				</section>
			</section>
			<!-- Second -->
			<section class="product-listing twelvecol last">
				<figure class="product-image threecol">
					<img src="/images/urns/classic-bronze.png" alt="atlantic-white">
				</figure>
				<section class="product-desc ninecol last">
					<header class="twelvecol last">
						<hgroup class="ninecol">
							<h5 class="product-title">
								Sterling 18 gauge steel
							</h5>
						</hgroup>
						<hgroup class="threecol last">
							<h6 class="product-price">$2720</h6>
						</hgroup>
					</header>
					<article class="product-details">
						<p>Antique White Shaded Silver Rose finish with Pink Crepe interior, also comes in Black Cherry, Empire Blue, Grecian Gold and Storm Blue finish</p>
					</article>
				</section>
			</section>
			<!-- Second -->
			<section class="product-listing twelvecol last">
				<figure class="product-image threecol">
					<img src="/images/urns/twilight.jpg" alt="atlantic-white">
				</figure>
				<section class="product-desc eightcol last">
					<header class="twelvecol last">
						<hgroup class="ninecol">
							<h5 class="product-title">
								Sterling 18 gauge steel
							</h5>
						</hgroup>
						<hgroup class="threecol last">
							<h6 class="product-price">$2720</h6>
						</hgroup>
					</header>
					<article class="product-details">
						<p>Antique White Shaded Silver Rose finish with Pink Crepe interior, also comes in Black Cherry, Empire Blue, Grecian Gold and Storm Blue finish</p>
					</article>
				</section>
			</section>
			<!-- Second -->
			<section class="product-listing twelvecol last">
				<figure class="product-image threecol">
					<img src="/images/urns/essence-rose.png" alt="atlantic-white">
				</figure>
				<section class="product-desc eightcol last">
					<header class="twelvecol last">
						<hgroup class="ninecol">
							<h5 class="product-title">
								Sterling 18 gauge steel
							</h5>
						</hgroup>
						<hgroup class="threecol last">
							<h6 class="product-price">$2720</h6>
						</hgroup>
					</header>
					<article class="product-details">
						<p>Antique White Shaded Silver Rose finish with Pink Crepe interior, also comes in Black Cherry, Empire Blue, Grecian Gold and Storm Blue finish</p>
					</article>
				</section>
			</section>
			<!-- Second -->
			<section class="product-listing twelvecol last">
				<figure class="product-image threecol">
					<img src="/images/urns/Amethyst.jpg" alt="atlantic-white">
				</figure>
				<section class="product-desc eightcol last">
					<header class="twelvecol last">
						<hgroup class="ninecol">
							<h5 class="product-title">
								Sterling 18 gauge steel
							</h5>
						</hgroup>
						<hgroup class="threecol last">
							<h6 class="product-price">$2720</h6>
						</hgroup>
					</header>
					<article class="product-details">
						<p>Antique White Shaded Silver Rose finish with Pink Crepe interior, also comes in Black Cherry, Empire Blue, Grecian Gold and Storm Blue finish</p>
					</article>
				</section>
			</section>

		</section>
	</section>
	<section class="clear-15"></section>
</section>