<?php echo $this->doctype(); ?>
<html>
<head>
	<?php echo $this->headTitle(); ?>
	<!-- CSS -->
	<?php echo $this->headLink(); ?>
	<!-- JS -->
	<?php echo $this->headScript(); ?>
</head>
<body>

	<!-- Phone Number -->
	<section id="phone-number" class="row">
		<figure class="twelvecol last">
			<img src="/images/phone_number.png" alt="503.526.3952" />
		</figure>
	</section>

	<!-- Header -->	
	<header id="site-header" class="container">
		<section id="site-nav" class="row">
			<figure id="site-logo" class="threecol">
				<img src="/images/logo.png" alt="Threadgill Memorial Services" />
			</figure>
			<nav class="ninecol last">
				<ul>
					<li><a href="#">About Us</a></li>
					<li><a href="#">Products</a></li>
					<li><a href="#">Obituaries</a></li>
					<li><a href="#">Testimonials</a></li>
					<li><a href="#">Contact Us</a></li>
				</ul>
			</nav>
		</section>
	</header>

	<!-- Content -->
	<section id="site-content" class="row">
		<section id="intro-content">
			<section id="slide-show">
				<figure>
					<img src="/images/welcome.png" alt="Welcome to Threadgill Memorial Services">
				</figure>
			</section>
		</section>
	</section>

	<!-- Footers -->
	<footer id="site-footer" class="container">
		<section id="intro-footer" class="row">
			<section id="col-1" class="fourcol column">
				<header>
					<hgroup>
						<img src="/images/flower.png" alt="flower">
						<h2 class="column-header">Quick Link <br />Goes Here</h2>
					</hgroup>
					<article>
						Etiam sit amet dui eu nisl tempus pharetra tristique sed mi. Curabitur quis arcu auctor neque mollis faucibus. Aliquam dui felis, fringilla vitae placerat vitae, lobortis ullamcorper ante. 
					</article>
				</header>
				<article>
					<p>
						Sed eu volutpat massa. Praesent eleifend accumsan nulla sit amet dictum. Aenean sit amet dolor at velit feugiat adipiscing in vel leo. Nam sit amet sagittis odio. Cras ipsum arcu, semper eget rutrum ac, ultrices vel elit. In auctor ultrices sapien, ac tempor metus volutpat a. Nunc consectetur adipiscing ipsum, id tristique turpis consequat in. Sed elementum tortor in libero egestas et dapibus ipsum volutpat.
					</p>
					<p>
						Etiam sit amet dui eu nisl tempus pharetra tristique sed mi. Curabitur quis arcu auctor neque mollis faucibus. Aliquam dui felis, fringilla vitae placerat vitae, lobortis ullamcorper ante. Nullam volutpat nulla non tellus sodales adipiscing. Maecenas at metus nunc, et aliquet dolor. Phasellus vel hendrerit risus. Maecenas id justo mattis nunc vestibulum gravida.
					</p>
				</article>
			</section>
			<section id="col-2" class="fourcol column">
			</section>
			<section id="col-3" class="fourcol column last">
			</section>
		</section>
	</footer>
</body>
</html>