<?php echo $this->doctype(); ?>
<html>
<head>
	<?php echo $this->headTitle(); ?>
	<!-- CSS -->
	<?php echo $this->headLink(); ?>
	<!-- JS -->
	<?php echo $this->headScript(); ?>
</head>
<body>

	<!-- Phone Number -->
	<section id="headline" class="row">
		<figure class="threecol">
			<img src="/images/phone_number.png" alt="503.526.3952" />
		</figure>
		<section id="icons" class="ninecol last">
			<ul class="sm-icons-list">
				<li><a href="http://www.facebook.com/ThreadgillMemorialServices" target="_blank"><img src='/images/facebook.png' alt="Follow us on facebook"></a></li>
				<li><a href="http://www.linkedin.com/in/ronlthreadgill" target="_blank"><img src='/images/linked_in.png' alt="Connect on Linked In"></a><li>
				<li><a href="https://plus.google.com/u/0/111294780426327454234/posts" target="_blank"><img src="/images/g-plus.png" alt="Check us out on G+"></a></li>
			</ul>
		</section>
	</section>

	<!-- Header -->	
	<header id="site-header" class="container">
		<section id="site-nav" class="row">
			<figure id="site-logo" class="threecol">
				<img src="/images/logo.png" alt="Threadgill Memorial Services" />
			</figure>
			<nav class="ninecol last">
				<ul>
					<li><a href="#">About Us</a></li>
					<li><a href="#">Products</a></li>
					<li><a href="#">Obituaries</a></li>
					<li><a href="/forms">Forms</a></li>
					<li><a href="#">Testimonials</a></li>
					<li><a href="#">Contact Us</a></li>
				</ul>
			</nav>
		</section>
	</header>

	<!-- Content -->
	<section id="site-content" class="row">
		<?php echo $this->layout()->content; ?>
	</section>

	<!-- Footers -->
	<footer id="site-footer" class="container">
		<section id="intro-footer" class="row">
			<section id="col-1" class="fourcol column">
				<header>
					<hgroup>
						<img src="/images/flower.png" alt="flower">
						<h2 class="column-header">Quick Link <br />Goes Here</h2>
					</hgroup>
					<article>
						<p>
							Etiam sit amet dui eu nisl tempus pharetra tristique sed mi. Curabitur quis arcu auctor neque mollis faucibus. Aliquam dui felis, fringilla vitae placerat vitae, lobortis ullamcorper ante. 
						</p>
					</article>
				</header>
				<article>
					<p>
						Sed eu volutpat massa. Praesent eleifend accumsan nulla sit amet dictum. Aenean sit amet dolor at velit feugiat adipiscing in vel leo. Nam sit amet sagittis odio. Cras ipsum arcu, semper eget rutrum ac, ultrices vel elit. In auctor ultrices sapien, ac tempor metus volutpat a. Nunc consectetur adipiscing ipsum, id tristique turpis consequat in. Sed elementum tortor in libero egestas et dapibus ipsum volutpat.
					</p>
					<p>
						Etiam sit amet dui eu nisl tempus pharetra tristique sed mi. Curabitur quis arcu auctor neque mollis faucibus. Aliquam dui felis, fringilla vitae placerat vitae, lobortis ullamcorper ante. Nullam volutpat nulla non tellus sodales adipiscing. Maecenas at metus nunc, et aliquet dolor. Phasellus vel hendrerit risus. Maecenas id justo mattis nunc vestibulum gravida.
					</p>
				</article>
			</section>
			<section id="col-2" class="fourcol column">
				<header>
					<hgroup>
						<img src="/images/flower.png" alt="flower">
						<h2 class="column-header">servicing the greater portland area</h2>
					</hgroup>
					<article>
						<p>
							Etiam sit amet dui eu nisl tempus pharetra tristique sed mi.  
						</p>
					</article>
				</header>
				<figure>
					<img src="/images/oregon_map.png" alt="Servicing the greater Portland Area and more!" >
				</figure>
				<section id='info-1' class="accordion">
					<header class="closed">
						<h4>Information 1</h1>
					</header> 
					<section class="accordion-content">

						<p>
							Sed eu volutpat massa. Praesent eleifend accumsan nulla sit amet dictum. Aenean sit amet dolor at velit feugiat adipiscing in vel leo.
						</p>

					</section>
				</section>
				<section id='info-2' class="accordion">
					<header class="closed">
						<h4>Information 2</h1>
					</header> 
					<section class="accordion-content">
						<p>
							Sed eu volutpat massa. Praesent eleifend accumsan nulla sit amet dictum. Aenean sit amet dolor at velit feugiat adipiscing in vel leo.
						</p>
					</section>
				</section>
				<section id='info-3' class="accordion">
					<header class="closed">
						<h4>Information 3</h1>
					</header> 
					<section class="accordion-content">
						<p>
							Sed eu volutpat massa. Praesent eleifend accumsan nulla sit amet dictum. Aenean sit amet dolor at velit feugiat adipiscing in vel leo.
						</p>
					</section>
				</section>
			</section>
			<section id="col-3" class="fourcol column last">
			<header>
				<hgroup>
					<img src="/images/flower.png" alt="flower">
					<h2 class="column-header">Quick Link <br />Goes Here</h2>
				</hgroup>
			</header>
			<section id="veterans" class="sub-menu">
				<figure>
					<a href="#"><img src="/images/veterans.png" alt="We take special care of our great veterans"></a>
				</figure>
				<article>
					<a href="#"><h2>Class Lexinon 4821</h2></a>
					<p>
						Sed eu volutpat massa. Praesent eleifend accumsan nulla sit amet dictum. Aenean sit amet dolor at velit feugiat adipiscing in vel leo. 
					</p>	
				</article>
				<div class="clear-15"></div>
			</section>
			<section id="Instruction" class="sub-menu">
				<figure>
					<a href="#"><img src="/images/flowers_small.png" alt="We teach you everything you need to know!"></a>
				</figure>
				<article>
					<a href="#"><h2>Class Lexinon 4821</h2></a>
					<p>
						Sed eu volutpat massa. Praesent eleifend accumsan nulla sit amet dictum. Aenean sit amet dolor at velit feugiat adipiscing in vel leo. 
					</p>	
				</article>
				<div class="clear-15"></div>
			</section>
		</section>
	</section>
	</footer>
</body>
</html>