<section id="about-content" class="page-content">
	<header>
		<h1>About us at Threadgill Memorial</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol">
		<figure class="fancy-img rotated">
			<img src="/images/profile_sample.jpg" alt="About Us, Rond and Deborah Threadgill">
		</figure>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Who we are</h5>
			</hgroup>
		</header>
		<section>
			<article>
				<p>
					As owners, with more than 12 years of experience in the funeral industry, Ron &amp; Deborah are committed to helping families make the best decisions in a difficult time while conserving family resources.  We serve families by helping them to determine what their needs are. We therefore offer unique services to create everlasting memories and help families bridge their grief. 
				</p>
				<p>
					In addition to his funeral director's license, Ron has been an insurance agent and an insurance consultant for over 20 years. He offers honest advice on pre-arrangements and pre-paying funeral plans. Ron's background in estate planning complements his vast experience as a funeral director.  In addition, he has worked as a CNA and is very familiar with facilities and working with the staff. He has a B.A. in business and communications from Concordia University in Portland. 
				</p>
				<p>
					Before becoming a funeral director, Deborah worked in the hospice, home health and home care field as a billing specialist.  With a B.A in sociology and psychology from Rider University in New Jersey, she has a varied career as a probation officer; a counselor in a group home; retail store manager of Dilettante Chocolates in Seattle, WA and a teacher in a private school. 
				</p>
				<p>
					With their extensive experience working with people, and as the business owners and decision makers, Deborah and Ron Threadgill can solve problems and create memories beyond the scope of the typical funeral home. 
				</p>
				<p>
					They have a daughter, Kiera and a son, Kade who assist them in their business. Ron &amp; Deborah celebrated their 25th wedding anniversary in August, and feel that the next best thing to doing what you love, is doing it with your spouse.
				</p>
			</article>
		</section>
	</section>
	<section class="clear-15"></section>
</section>