<section id="about-content" class="page-content">
	<header>
		<h1>About us at Threadgill Memorial</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol">
		<figure>
			<img src="images/threadgill-bg.jpg" alt="About Us, Rond and Deborah Threadgill">
		</figure>
	</section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Who we are</h5>
			</hgroup>
		</header>
		<section class="sub-content-wrapper">
			<article>
				<p>
					As owners, with more than 12 years of experience in the funeral industry, Ron &amp; Deborah are committed to helping families make the best decisions in a difficult time while conserving family resources.  We serve families by helping them to determine what their needs are. We therefore offer unique services to create everlasting memories and help families bridge their grief. 
				</p>
				<p>
					In addition to his funeral director's license, Ron has been an insurance agent and an insurance consultant for over 20 years. He offers honest advice on pre-arrangements and pre-paying funeral plans. Ron's background in estate planning complements his vast experience as a funeral director.  In addition, he has worked as a CNA and is very familiar with facilities and working with the staff. He has a B.A. in business and communications from Concordia University in Portland. 
				</p>
				<p>
					Before becoming a funeral director, Deborah worked in the hospice, home health and home care field as a billing specialist.  With a B.A in sociology and psychology from Rider University in New Jersey, she has a varied career as a probation officer; a counselor in a group home; retail store manager of Dilettante Chocolates in Seattle, WA and a teacher in a private school. 
				</p>
				<p>
					With their extensive experience working with people, and as the business owners and decision makers, Deborah and Ron Threadgill can solve problems and create memories beyond the scope of the typical funeral home. 
				</p>
				<p>
					They have a daughter, Kiera and a son, Kade who assist them in their business. Ron &amp; Deborah celebrated their 25th wedding anniversary in August, and feel that the next best thing to doing what you love, is doing it with your spouse.
				</p>
			</article>
			<article>
				<p>
					Threadgill Memorial Services takes great effort to honor and support a family who has lost a loved one!  It is important to understand "family culture" and family dynamics while making choices and considering options.
				</p>
				<p>
					When making decisions, it is important to note that there is not an economic requirement for services to meet each family member’s needs.  What is required is communication, consideration and respect.
				</p>
				<p>
					We honor and usher the individuals and families through this difficult process and assist them in bridging their future needs and current feelings with the present.
				</p>
				<p>
					We make funeral arrangements in the homes of the families we serve or a place of their choosing allowing them to be more comfortable. 
				</p>
				<p>
					We facilitate funerals all over the Portland area assisting families in staying close to their homes or the cemetery of their choice.  We have also facilitated funerals in Washington, Oregon, Idaho, Utah and California.  
				</p>
				<p>
					We have transported casketed and cremated human remains throughout the United States and several foreign countries.     
				</p>
			</article>
		</section>
	</section>
	<section class="clear-15"></section>
</section>