<section id="contact-content" class="page-content">
	<header>
		<h1>Contact Threadgill Memorial Services</h1>
	</header>
	<section class="clear-15"></section>
	<section class="page-menu threecol">
		<section>
			<hgroup>
				<h6>--- Contact Info ---</h6>
			</hgroup>
			<ul>
				<li>Phone Number</li>
				<li>Mailing address</li>
				<li>Other Info</li>
			</ul>
		</section>
	</section>
	<section id="contact-form-wrapper" class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Fill out the form below to contact us!</h5>
			</hgroup>
		</header>
		<section id="contact-form" class="">
			<form action="/contact/submit" method="POST">
				<ul>
					<!-- First Row -->
					<li>
						<ul>
							<li class="wrapper-43"><input type="text" name="first-name" placeholder="First Name"></li>
							<li class="wrapper-53"><input type="text" name="last-name" placeholder="Last Name"></li>
						</ul>
					</li>
					<!-- Second Row -->
					<li>
						<ul>
							<li class="wrapper-43"><input type="email" name="email" placeholder="Email Address"></li>
							<li class="wrapper-53"><input type="phone" name="phone" placeholder="Phone Number"></li>
						</ul>
					</li>
					<!-- Third Row -->
					<li>
						<ul>
							<li class="wrapper-43 flush"><label for="inquiry">Type your question or comment below:</label></li>
						</ul>
					</li>
					<!-- Fourth Row -->
					<li class="flush wrapper-75"><textarea rows="10"></textarea></li>
					<!-- Fifth Row -->
					<li>
						<ul>
							<li class="wrapper-20 flush"><input type="submit" value="Say Hello!"></li>
						</ul>
					</li>
				</ul>
			</form>
		</section>
	</section>
</section>