<section id="contact-content" class="page-content">
	<header>
		<h1>Thank You!</h1>
	</header>
	<section class="clear-15"></section>
	<section class="threecol"></section>
	<section class="ninecol last content-wrapper">
		<header>
			<hgroup>
				<h5>Thank you for your patronage!</h5>
			</hgroup>
		</header>
		<section>
			<header>
				<hgroup>
					<h6>We will contact you as soon as possible! Feel free to browse our site for a full listing of our products and services.</h6>
				</hgroup>
			</header>
		</section>
	</section>
	<section class="clear-15"></section>
</section>